# Generated by Django 3.2.5 on 2021-07-31 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('projects', '0001_initial'),
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_reports', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_reports', to='projects.project'),
        ),
    ]
